version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: nodepg
      POSTGRES_PASSWORD: 8sM*TLQ|zW.A
      PGPASSWORD: 8sM*TLQ|zW.A
      POSTGRES_DB: node_score
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: nontacques@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 8sM*TLQ|zW.A
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_score
    volumes:
      - /usr/src/node_modules
      - .:/usr/src/app
    command: yarn prod
    ports:
      - "3000:3000"
      - "5555:5555"


volumes:
  postgres:
  pgadmin: